version: "3"

services:
  web:
    build: .
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && gunicorn -w 1 --bind 0.0.0.0:8000 api.wsgi"
    container_name: mentorci
    volumes:
      - .:/mentorci
    ports:
      - "8000:8000"

